### ISSUE TITLE
IndexOutOfBoundsException when iterating to the next month

### ISSUE THREAD

**Issue by shawes** [shawes/zissou#11]
java.lang.IndexOutOfBoundsException: 2
	at scala.collection.LinearSeqOptimized.apply(LinearSeqOptimized.scala:63)
	at scala.collection.LinearSeqOptimized.apply$(LinearSeqOptimized.scala:61)
	at scala.collection.immutable.List.apply(List.scala:86)
	at physical.flow.FlowGridWrapper.getVelocity(FlowGridWrapper.scala:88)
	at maths.interpolation.Interpolation.apply(Interpolation.scala:29)
	at physical.flow.FlowController.getVelocityOfCoordinate(FlowController.scala:56)
	at maths.integration.RungeKuttaIntegration.integrate(RungeKuttaIntegration.scala:15)
	at model.BiologicalModel.moveParticle$1(BiologicalModel.scala:67)
	at model.BiologicalModel.move(BiologicalModel.scala:75)
	at model.BiologicalModel.biology(BiologicalModel.scala:56)
	at model.BiologicalModel.$anonfun$apply$1(BiologicalModel.scala:34)
	at model.BiologicalModel.$anonfun$apply$1$adapted(BiologicalModel.scala:34)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by shawes** [comment]
Fixed by changing the data structure from a list to a queue. #
